<?php
require dirname(__DIR__) . '/src/bootstrap.php';
$properties = search_properties($_GET);
page_header('Find your next chapter');
?>
<section class="hero"><div><p class="eyebrow">THOUGHTFUL HOMES. SIMPLE DISCOVERY.</p><h1>A little more space.<br>A new <em>perspective.</em></h1><p>Explore homes that fit the way you want to live.</p></div><div class="hero-stat"><strong>Find your place.</strong><span>Three neighborhoods.<br>Possibilities to explore.</span></div></section>
<form class="filters" method="get" action="index.php" aria-label="Filter properties">
<label>Search<input name="q" value="<?= e(field($_GET,'q')) ?>" placeholder="Name or keyword" maxlength="100"></label>
<label>Property type<select name="type" aria-label="Property type"><option value="">All types</option><?php foreach (PROJECT_TYPES as $value => $label): ?><option value="<?= e($value) ?>" <?= field($_GET,'type') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
<label>Neighborhood<select name="district" aria-label="Neighborhood"><option value="">All neighborhoods</option><?php foreach (DISTRICTS as $district): ?><option <?= field($_GET,'district') === $district ? 'selected' : '' ?>><?= e($district) ?></option><?php endforeach; ?></select></label>
<label>Maximum price<select name="max_price" aria-label="Maximum price"><option value="">Any budget</option><?php foreach ([3000000,5000000,8000000] as $price): ?><option value="<?= $price ?>" <?= field($_GET,'max_price') === (string)$price ? 'selected' : '' ?>>฿<?= number_format($price) ?></option><?php endforeach; ?></select></label>
<label>Sort by<select name="sort" aria-label="Sort by"><?php foreach (['price_asc'=>'Price: low to high','price_desc'=>'Price: high to low','newest'=>'Newest first'] as $value=>$label): ?><option value="<?= $value ?>" <?= field($_GET,'sort') === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<button class="button" type="submit">Find a home ↗</button><a class="reset" href="index.php">Reset filters</a></form>
<div class="results-heading"><h2>Homes to discover <span><?= count($properties) ?></span></h2><p>Showing up to 100 matching properties</p></div>
<div class="explore-layout"><section class="properties" aria-label="Property results">
<?php if (!$properties): ?><div class="empty"><h2>No homes match these filters.</h2><p>Try a different neighborhood, property type, or budget.</p><a class="button" href="index.php">View all homes</a></div><?php endif; ?>
<?php foreach ($properties as $index=>$property): ?><article class="property-card" id="property-<?= (int)$property['id'] ?>"><div class="property-art art-<?= e($property['type']) ?>" aria-hidden="true"><span class="art-label"><?= e($property['district']) ?></span><div class="building"><i></i><i></i><i></i></div><span class="art-number"><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span></div><div class="card-content"><span class="eyebrow"><?= e(PROJECT_TYPES[$property['type']]) ?></span><h3><a href="property.php?id=<?= (int)$property['id'] ?>"><?= e($property['name']) ?> <span aria-hidden="true">↗</span></a></h3><p class="property-price">฿<?= number_format((int)$property['price']) ?></p><div class="property-specs"><span><?= (int)$property['bedrooms'] ?> bedrooms</span><span><?= (int)$property['area'] ?> m²</span></div></div></article><?php endforeach; ?>
</section><aside class="map-panel"><div class="map-heading"><strong>A sense of place.</strong><span>Illustrative neighborhood map</span></div><div class="map" aria-label="Illustrative map of matching properties"><div class="park"></div><div class="river"></div><div class="road road-one"></div><div class="road road-two"></div><span class="map-label">NORTH QUARTER</span><span class="map-label garden">GARDEN DISTRICT</span><?php foreach ($properties as $index=>$property): ?><a class="map-pin" href="property.php?id=<?= (int)$property['id'] ?>" style="left:<?= (int)$property['map_x'] ?>%;top:<?= (int)$property['map_y'] ?>%" aria-label="View <?= e($property['name']) ?>"><?= $index+1 ?></a><?php endforeach; ?></div><p>Map numbers correspond to the property cards.<br>Locations are illustrative, not geographic coordinates.</p></aside></div>
<?php page_footer(); ?>
